### ISSUE TITLE
Stack Level Too deep error when using alpine ruby image

### ISSUE THREAD

**Issue by jottr** [docker-library/ruby#197] opened 2018-03-08 20:58 UTC
We get a `stack level too deep` error message, when running our `rspec` tests inside a container based on the alpine ruby image (`ruby:2.5.0-alpine`).

This does not happen when using an ubuntu image as base. 
It seems that this issue has already been reported on the [rspec bugtracker](https://github.com/rspec/rspec-support/issues/341), and on the ruby [bug tracker](https://bugs.ruby-lang.org/issues/14387). 
[This comment](https://bugs.ruby-lang.org/issues/14387#note-9) provides a testcase for what happens when ruby tries to calculate the stacksize inside an alpine container.

I created this issue, so we can track if this issue has been resolved here, or upstream by ruby devs or `musl-libc` devs

**Comment by yosifkit** [comment] 2018-03-08 22:15
Duplicate of #196

**Closed by yosifkit** 2018-03-08 22:15 UTC
