### ISSUE TITLE
2.4.2-alpine3.6 contains useless ruby libs in `/usr/lib`

### ISSUE THREAD

**Issue by ojab** [docker-library/ruby#160] opened 2017-09-21 08:35 UTC
Even though `ruby` from `/usr/local` is used, image contains additional ruby libraries in `/usr/lib`:  
```
$ docker run --rm -ti ruby:2.4-alpine3.6 du -csh /usr/lib/ruby /usr/lib/libruby.so.2.4.2
10.1M   /usr/lib/ruby
2.1M    /usr/lib/libruby.so.2.4.2
12.2M   total
```
AFAIU they are not used at all and can be safely removed.

**Comment by yosifkit** [comment] 2017-09-21 17:01
Duplicate of https://github.com/docker-library/ruby/pull/131.

**Closed by yosifkit** 2017-09-21 17:01 UTC
