### ISSUE TITLE
Block the installation of Debian's Ruby packages

### ISSUE THREAD

**Issue by J0WI** [docker-library/ruby#336] opened 2021-01-14 15:31 UTC
Similar to https://github.com/docker-library/php/pull/542

**Comment by tianon** [comment] 2021-01-14 23:14
This is somewhat reasonable, but I worry that we're solving a problem that doesn't appear to be as common as it does in the PHP community?

In the PHP case, we added that specifically because we kept getting reports of and seeing users installing `php-foo` and expecting that it would somehow work -- we don't see very many similar reports in the Ruby community (probably because installing Ruby extensions is generally more straightforward vs the hackery we did with `docker-php-ext-*` in the PHP world due to limitations in how PHP itself is developed).

**Comment by J0WI** [comment] 2021-01-15 01:08
I agree that it's not very common. I only spotted it [here](https://github.com/danmunn/redmine_dmsf/issues/329)/[here](https://github.com/danmunn/redmine_dmsf/issues/769).

**Comment by tianon** [comment] 2021-08-20 23:43
Aha, this is a duplicate of #139 :sweat_smile:

**Closed by tianon** 2021-08-20 23:43 UTC
Labels: Request
