### ISSUE TITLE
Error when running "apt-get update" in ruby:2.3.1-slim

### ISSUE THREAD

**Issue by maierovidiu** [docker-library/ruby#276] opened 2019-03-29 14:23 UTC
Dockerfile with 
FROM ruby:2.3.1-slim
RUN apt-get update

returns "Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found"

**Comment by dentarg** [comment] 2019-03-29 15:50
This is due to https://github.com/docker-library/ruby/issues/275. I can't imagine that @tianon and @yosifkit will be rebuilding old images to fix this. ruby:2.3.8-slim-jessie works.

**Comment by tianon** [comment] 2019-03-29 16:00
> can't imagine .. will be rebuilding old images to fix this.

Spot on :heart: -- Ruby doesn't support old Ruby versions, and thus we don't either (meaning they don't get rebuilds).

Closing as a duplicate of #275.

**Closed by tianon** 2019-03-29 16:00 UTC
