### ISSUE TITLE
gitlab-ci.yml - dpl: command not found error

### ISSUE THREAD

**Issue by Sklico** [docker-library/ruby#214] opened 2018-05-24 20:39 UTC
This is my gitlab-ci.yml file:
```
image: ruby:latest

stages:
  - deploy

deploy_master:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - master
  when: on_success

deploy_test:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_TEST_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - test
  when: on_success
```
And this is output from pipeline:
```
Checking out 2c69d48d as test...
Skipping Git submodules setup
$ gem install dpl
Successfully installed dpl-1.9.6
1 gem installed
$ dpl --provider=heroku --app=$HEROKU_TEST_APP_NAME --api-key=$HEROKU_API_KEY
/bin/bash: line 57: dpl: command not found
ERROR: Job failed: exit code 1

```

It worked yesterday, but today, it still fails on dpl command. I've tried different ruby images, but nothing changed. It works, when I use a little workaround and use this in my gitlab-ci file:
- export PATH=$PATH:/usr/local/bundle/bin

**Comment by yosifkit** [comment] 2018-05-24 20:41
Duplicate of #211 and #212, fixed by #209.

**Closed by yosifkit** 2018-05-24 20:41 UTC

**Comment by Sklico** [comment] 2018-05-24 20:45
@yosifkit  - I'm sorry, I saw that issues before, but as I understand, the fix should be merged and It still doesn't work for me, so I thought, it's different problem.

**Comment by yosifkit** [comment] 2018-05-24 20:47
(https://github.com/docker-library/ruby#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet)

https://github.com/docker-library/official-images/pull/4391 :+1:

**Comment by tianon** [comment] 2018-05-24 21:03
Once they're merged there, they need to build/push -- see https://doi-janky.infosiftr.net/job/multiarch/view/images/view/ruby/, specifically https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/ruby/.
