### ISSUE TITLE
Warn users on README about encoding default.

### ISSUE THREAD

**Issue by lfundaro** [docker-library/ruby#70] opened 2016-02-16 09:58 UTC
I was trying to dockerize a ruby project that uses UTF-8 encoding and struggled with encoding issues because didn't know that [Debian Jessie dropped the dependency on locales package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=636086#3) as @oncletom suggests it [here](https://oncletom.io/2015/docker-encoding/). This is a problem that might not be very obvious to the user. 

It's not enough to simply add on your Dockerfile `ENV  LANG en_US.UTF-8`. 

I would suggest to make a section on the README warning users about this gotcha and telling them to use `ENV LANG C.UTF-8` instead or 

```
#> apt-get update && apt-get install locales
#> locale-gen
#> dpkg-reconfigure locales
```

what do you think about ?

**Comment by Quintasan** [comment] 2018-12-05 13:21
Can't we set this to `C.UTF-8` by default? I just ran bash in `ruby:2.5` image and `C.UTF-8` is present inside. What's the rationale for keeping it set to `POSIX`?

**Comment by yosifkit** [comment] 2018-12-05 22:42
Duplicate of https://github.com/docker-library/ruby/issues/45.

Closed by https://github.com/docker-library/docs/pull/689

**Closed by yosifkit** 2018-12-05 22:42 UTC
Labels: Request
