### ISSUE TITLE
jmalloc ?

### ISSUE THREAD

**Issue by grosser** [docker-library/ruby#201] opened 2018-03-22 23:27 UTC
would you accept a PR to add ruby-2.5.0-alpine-jmalloc (or whatever the name would be) ?

got it working with this simplistic Dockerfile, but would try to edit the existing one in the repo to add a flag to install jmalloc optionally

```
FROM alpine

WORKDIR /

# 1 line to remove unnecessary build tools and reduce image size
RUN apk add --update --no-cache --virtual ruby-dependencies \
    linux-headers build-base bash libc-dev readline-dev jemalloc-dev libressl-dev && \

    wget -O ruby-install-0.6.1.tar.gz https://github.com/postmodern/ruby-install/archive/v0.6.1.tar.gz && \

    tar -xzvf ruby-install-0.6.1.tar.gz && \
    cd ruby-install-0.6.1/ && \
    make install && \

    ruby-install --system ruby 2.5.0 && \

    make uninstall && \
    cd / && rm -rf ruby-install-0.6.1 && \

    apk del ruby-dependencies

RUN echo "gem: --no-document" > ~/.gemrc

RUN gem install bundler
```

**Comment by tianon** [comment] 2018-03-23 02:33
Duplicate of #182 :wink:

**Closed by tianon** 2018-03-23 02:33 UTC

**Comment by grosser** [comment] 2018-03-23 03:00
FYI dug further and this example does not work ... 

`docker run + ruby -r rbconfig -e RbConfig::CONFIG\[\'LIBS\'\].include\?\(\'jemalloc\'\)\ \?\ puts\(\'Ruby\ is\ compiled\ with\ jemalloc\'\)\ :\ warn\(\'JEMALLOC\ IS\ MISSING\ FROM\ RUBY\'\)`
JEMALLOC IS MISSING FROM RUBY

... tried a bunch of config options without success :/
