### ISSUE TITLE
Mastodon (sidekick) crashing under Ruby 2.5.1 on Alpine 3.7

### ISSUE THREAD

**Issue by ashleyhull-versent** [docker-library/ruby#236] opened 2018-09-19 01:15 UTC
I'm raising this ticket to raise concerns with the sigfaulting of sidekick on mastodon. This is easily replicated.

This was originally documented here https://github.com/tootsuite/mastodon/issues/6734
but I don't believe it was followed up with the sidekick or Ruby docker/alpine teams.

**Comment by ashleyhull-versent** [comment] 2018-09-19 01:17
https://github.com/tootsuite/mastodon/pull/8712 is my revert due to sigfaults. This pull includes my crash report logs in full.

    mastodon@ip-10-0-0-140:~$ docker container logs dd6cc8b27859 > crash
    /mastodon/vendor/bundle/ruby/2.5.0/gems/rdf-3.0.2/lib/rdf/model/statement.rb:332: [BUG] Segmentation fault at 0x00007efcb3517bc0
    ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-musl]

    /mastodon/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.8.4/lib/nokogiri/html/document.rb:150: [BUG] Segmentation fault at 0x00007f8200e79bc0
    ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-musl]

**Comment by tianon** [comment] 2018-09-19 20:33
Does it also reproduce on 2.4 and/or 2.6?  If so, does it _also_ reproduce with Alpine's Ruby package in place of our compiled Ruby? (https://pkgs.alpinelinux.org/package/v3.7/main/x86_64/ruby)

I'm still not sure there's much/anything *we* can really do here, and think this probably needs to be escalated to either the Alpine maintainers (if it can be reproduced with Alpine packages) or to the Ruby maintainers (unless it does _not_ reproduce on Ruby 2.6 or Alpine 3.8, in which case it's very likely already fixed in Ruby upstream or Alpine upstream respectively).

**Comment by tianon** [comment] 2018-10-02 00:44
(Closing, since I don't think there's anything we can do here -- we build a pretty stock Ruby from upstream's sources, so this is something that really needs to be fixed in Ruby itself.)

**Closed by tianon** 2018-10-02 00:44 UTC
