### ISSUE TITLE
Cannot switch bundler version

### ISSUE THREAD

**Issue by theplayer777** [docker-library/ruby#286] opened 2019-07-10 09:58 UTC
Hello,

I know that there's already a lot of topics on that subjet, but I read most of them without being able to solve my issue. It seems that I still have 2 version of bundle installed, even if I uninstall the default version and reinstall the 2.0.1:

```
RUN gem uninstall bundler -v '1.17.2'
RUN gem install bundler -v '2.0.1'
RUN bundle install 
CMD ["bundle", "exec", "puma", "-C", "puma.rb"]
```
result is _Could not find 'bundler' (2.0.1) required by your Gemfile.lock_

I even try to delete the Gemfile.lock. It seems to be generated correctly during the image build:

```
GEM
  remote: https://rubygems.org/
  specs:
  [...]
BUNDLED WITH
   2.0.1 <------------------------------------------------------
```

but it still results to the same error, as if CMD was using a different version of bundler compared to RUN. If I bash into the container, I cannot see any version of bundler other than 2.0.1:

```
$ find / -name bundler
/usr/local/lib/ruby/2.6.0/bundler
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundler
/usr/local/bin/bundler
/usr/local/bundle/gems/bundler-2.0.1/lib/bundler
/usr/local/bundle/gems/bundler-2.0.1/exe/bundler
/usr/local/bundle/gems/capistrano-bundler-1.5.0/lib/capistrano/bundler
/usr/local/bundle/bin/bundler

$ /usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundler -v
Bundler version 2.0.1
$ /usr/local/bundle/bin/bundler -v
Bundler version 2.0.1
$ /usr/local/bin/bundler -v
Bundler version 2.0.1
```

I tried with many image version from 2.5.5 to 2.7 without any luck.

Thanks in advance for your help

**Comment by yosifkit** [comment] 2019-07-10 20:55
The image comes with the `bundler` that is bundled with ruby itself. You'll notice that the uninstall does nothing even though it shows up in the `gem list`:
```console
$ docker run -it --rm ruby:2.5.5 bash
root@f445b3c5309b:/# gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.3.4)
bundler (default: 1.17.3)
cmath (default: 1.0.0)
csv (default: 1.0.0)
date (default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.2.0)
etc (default: 1.0.0)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
gdbm (default: 2.0.0)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
json (default: 2.1.0)
minitest (5.10.3)
net-telnet (0.1.1)
openssl (default: 2.1.2)
power_assert (1.1.1)
psych (default: 3.0.2)
rake (12.3.0)
rdoc (default: 6.0.1)
rubygems-update (3.0.3)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
test-unit (3.2.7)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
zlib (default: 1.0.0)
root@f445b3c5309b:/# gem uninstall bundler -v '1.17.2'
Gem 'bundler' is not installed
```

The 1.17.3 bundler from ruby does not provide the `bundler` binary, just `bundle`:
```console
root@84cd3ff39e69:/# find / -name bundle* | grep -v man
/usr/lib/python2.7/dist-packages/bzrlib/bundle
/usr/lib/python2.7/dist-packages/bzrlib/bundle/bundle_data.pyc
/usr/lib/python2.7/dist-packages/bzrlib/bundle/bundle_data.py
/usr/lib/python2.7/dist-packages/mercurial/bundle2.pyc
/usr/lib/python2.7/dist-packages/mercurial/bundlerepo.py
/usr/lib/python2.7/dist-packages/mercurial/bundle2.py
/usr/lib/python2.7/dist-packages/mercurial/bundlerepo.pyc
/usr/share/mercurial/help/internals/bundles.txt
/usr/local/lib/ruby/site_ruby/2.5.0/bundler
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/bundler_version_finder.rb
/usr/local/lib/ruby/site_ruby/2.5.0/bundler.rb
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.3
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/exe/bundle
/usr/local/lib/ruby/gems/2.5.0/gems/rubygems-update-3.0.3/lib/rubygems/bundler_version_finder.rb
/usr/local/lib/ruby/gems/2.5.0/gems/rubygems-update-3.0.3/bundler
/usr/local/lib/ruby/gems/2.5.0/gems/rubygems-update-3.0.3/bundler/lib/bundler
/usr/local/lib/ruby/gems/2.5.0/gems/rubygems-update-3.0.3/bundler/lib/bundler.rb
/usr/local/lib/ruby/gems/2.5.0/gems/rubygems-update-3.0.3/bundler/exe/bundler
/usr/local/lib/ruby/gems/2.5.0/gems/rubygems-update-3.0.3/bundler/exe/bundle
/usr/local/lib/ruby/gems/2.5.0/gems/rubygems-update-3.0.3/bundler/exe/bundle_ruby
/usr/local/lib/ruby/gems/2.5.0/gems/rubygems-update-3.0.3/bundler/bundler.gemspec
/usr/local/lib/ruby/gems/2.5.0/specifications/default/bundler-1.17.3.gemspec
/usr/local/lib/ruby/2.5.0/rubygems/bundler_version_finder.rb
/usr/local/bin/bundle
/usr/local/bundle
```

Adding bundler 2.0.1, does add new `bundler` that masks the other and as far as I can tell is supposed to automatically use the right one.
```console
root@ea39f9d5b927:/# gem install bundler -v '2.0.1'
Fetching bundler-2.0.1.gem
Successfully installed bundler-2.0.1
1 gem installed
root@ea39f9d5b927:/# bundle -v
Bundler version 2.0.1
root@ea39f9d5b927:/# bundler -v
Bundler version 2.0.1
root@ea39f9d5b927:/# gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.3.4)
bundler (2.0.1, default: 1.17.3)
cmath (default: 1.0.0)
csv (default: 1.0.0)
date (default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.2.0)
etc (default: 1.0.0)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
gdbm (default: 2.0.0)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
json (default: 2.1.0)
minitest (5.10.3)
net-telnet (0.1.1)
openssl (default: 2.1.2)
power_assert (1.1.1)
psych (default: 3.0.2)
rake (12.3.0)
rdoc (default: 6.0.1)
rubygems-update (3.0.3)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
test-unit (3.2.7)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
zlib (default: 1.0.0)
```

Are you setting any environment or other config (what is the rest of the Dockerfile)? I was unable to reproduce anything similar with a simple `Gemfile` after installing `2.0.1`.
```Dockerfile
FROM ruby:2.5.5
RUN gem install bundler -v '2.0.1' && gem list
WORKDIR /app
RUN set -eux; \
	{ \
		echo 'source "https://rubygems.org"'; \    
		echo 'gem "rails"'; \
	} > Gemfile
RUN bundle install
RUN cat Gemfile.lock
RUN set eux; \
	bundle exec rails new /app
```

**Comment by chadwilken** [comment] 2019-07-17 22:02
I am also hitting this issue. I am attempting to use this in another dockerfile as the base image and when I do:
```
RUN gem install bundler
RUN bundle install
```

It says that it installed bundler 2.0.2 but when `bundle install` runs it says that the version of bundler if 1.16.1

```
 ---> 9aa197dc06b3
Step 7/9 : RUN gem install bundler

---> Running in dae3ab226001
Successfully installed bundler-2.0.2
1 gem installed

Removing intermediate container dae3ab226001
---> 54348f6c2265
Step 8/9 : RUN bundle install

---> Running in 688704d6b1a8
Warning: the running version of Bundler (1.16.1) is older than the version that created the lockfile (1.17.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
```

Then I get an error because this version of bundler isn't reading auth info from the ENV var I have set.

**Comment by yosifkit** [comment] 2019-07-17 22:58
@chadwilken:
> Are you setting any environment or other config (what is the rest of the Dockerfile )? I was unable to reproduce anything similar with a simple Gemfile after installing 2.0.1.

I've now even tested adding `gem install bundler` to the redmine image and it was fine as long as `gem install bundler` and `bundle install` was run as the same user.

**Comment by chadwilken** [comment] 2019-07-18 14:47
@yosifkit the full Dockerfile:
```
FROM ruby:2.5.0

ARG GRAPHQL_PRO_CREDS
ENV BUNDLE_GEMS__GRAPHQL__PRO $GRAPHQL_PRO_CREDS

RUN mkdir /app
WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler
RUN bundle install

COPY . /app
```

**Comment by yosifkit** [comment] 2019-07-18 20:29
@chadwilken: `ruby:2.5.0`, that is a fairly old version of Ruby 2.5 and hasn't been supported for quite some time. The most likely cause of your issue is that it doesn't have the fix for #246 (i.e. #255). You should either update to a ruby image that does have the fix or you might be able to work around it by setting `ENV BUNDLER_VERSION=`.

@theplayer777 does this also help you? :point_up: Are you using an older version of the ruby image?

**Comment by andreynering** [comment] 2019-07-30 13:39
I also had a lot of difficulty trying to use Bundler 2 with Ruby 2.3.1

I had to add both of these lines to make it work:

```dockerfile
ENV BUNDLER_VERSION='2.0.2'
RUN gem install bundler --no-document -v '2.0.2'
```

**Comment by tianon** [comment] 2019-09-06 16:24
Closing since this appears to be due to using an old (unsupported) version of the image (likely one affected by #246).

**Closed by tianon** 2019-09-06 16:24 UTC
Labels: question
