### ISSUE TITLE
ruby:3.2.0-slim-bullseye is not YJIT enabled

### ISSUE THREAD

**Issue by rubys** [docker-library/ruby#401] opened 2023-01-09 01:31 UTC
```
# ruby --yjit -v
ruby: warning: Ruby was built without YJIT support. You may need to install rustc to build Ruby with YJIT.
ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]
```

```
# irb
irb(main):001:0> RubyVM::YJIT.enabled?
(irb):1:in `<main>': uninitialized constant RubyVM::YJIT (NameError)
	from /usr/local/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
	from /usr/local/bin/irb:25:in `load'
	from /usr/local/bin/irb:25:in `<main>'
```

From https://hub.docker.com/_/ruby :

> These images have clear documentation, promote best practices, and are designed for the most common use cases.

Shouldn't YJIT be enabled?

**Comment by tianon** [comment] 2023-01-09 18:27
Duplicate of https://github.com/docker-library/ruby/pull/398, see also https://github.com/docker-library/ruby/pull/400

**Closed by tianon** 2023-01-09 18:27 UTC
