### ISSUE TITLE
 ruby:2-stretch uses jessie?

### ISSUE THREAD

**Issue by SpringMT** [docker-library/ruby#216] opened 2018-06-06 06:15 UTC
ruby:2-stretch uses jessie?

```
% docker run -it ruby:2-stretch /bin/bash
Unable to find image 'ruby:2-stretch' locally
2-stretch: Pulling from library/ruby
Digest: sha256:7bf2aa93875fc6ad5262a69aa26db062bdca2bf60901194a96137ab87306c674
Status: Downloaded newer image for ruby:2-stretch
root@b82e4fba349d:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)" <----- jessie????
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by gucki** [comment] 2018-06-06 07:15
I just noticed the same because our build failed to install some packages:

    $ docker run -it ruby:2.5-stretch /bin/bash
    root@e5a598b057e4:/# apt-get update
    Get:1 http://security.debian.org jessie/updates InRelease [94.4 kB]

**Comment by gucki** [comment] 2018-06-06 07:21
Btw, it doesn't look like an upstream bug:

    $ docker run -it buildpack-deps:stretch /bin/bash
    Unable to find image 'buildpack-deps:stretch' locally
    stretch: Pulling from library/buildpack-deps
    cc1a78bfd46b: Already exists 
    d2c05365ee2a: Pull complete 
    231cb0e216d3: Pull complete 
    3d2aa70286b8: Pull complete 
    e80dfb6a4adf: Pull complete 
    Digest: sha256:37f2e64f1401c832712ba95d550fe07605e7068773b04feb91a70f6b86056c42
    Status: Downloaded newer image for buildpack-deps:stretch
    root@20ac9ac894f4:/# cat /etc/os-release
    PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
    NAME="Debian GNU/Linux"
    VERSION_ID="9"
    VERSION="9 (stretch)"
    ID=debian
    HOME_URL="https://www.debian.org/"
    SUPPORT_URL="https://www.debian.org/support"
    BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by SpringMT** [comment] 2018-06-06 07:26
Latest Dockerfile in github sets `stretch` .
https://github.com/docker-library/ruby/blob/ecb78337005eb49371c4faf5f79d2675382d487a/2.5/stretch/Dockerfile#L1

I think the problem happened in image building process.

**Comment by gucki** [comment] 2018-06-06 07:36
Btw, for a temporary workaround until this is fixed one can update the own Dockerfile like this:

    # FROM ruby:2.5-stretch
    FROM ruby@sha256:07ae38136a1bcc4a14bc4fcdbd675575fc697ff21ee05417581548ed01f55645

The sha listed above is the latest working version known to me. Not sure if there's a later one working.

**Comment by klaustopher** [comment] 2018-06-06 08:02
> The sha listed above is the latest working version known to me. Not sure if there's a later one working.

I can confirm that this was the latest sha that was working about 5 hours ago.

**Comment by yosifkit** [comment] 2018-06-06 18:28
Looks like there was a bug in the build server that caused `buildpack-deps:jessie` to be tagged as `buildpack-deps:stretch`. :disappointed:  We have pushed a fix (https://github.com/docker-library/oi-janky-groovy/commit/5a4fab6c423b6790a253bf6a0beb32ad4946b983) and ruby is already in the build queue from https://github.com/docker-library/official-images/pull/4430.

**Comment by SpringMT** [comment] 2018-06-07 00:53
Great!
Latest ruby:2-stretch uses stretch.

```
% docker run --rm -it ruby:2-stretch /bin/bash
Unable to find image 'ruby:2-stretch' locally
2-stretch: Pulling from library/ruby
cc1a78bfd46b: Pull complete 
d2c05365ee2a: Pull complete 
231cb0e216d3: Pull complete 
3d2aa70286b8: Pull complete 
e80dfb6a4adf: Pull complete 
9fdce3e4507c: Pull complete 
590d63dda050: Pull complete 
e6fd54c4bb16: Pull complete 
Digest: sha256:15cf422c8a386c5dc4ffc51875d09f3e70a9350575aabe710117de452ec36159
Status: Downloaded newer image for ruby:2-stretch
root@18bd020a2d22:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Thx!

**Closed** 2018-06-07 00:53 UTC
Labels: Issue
