### ISSUE TITLE
bundle command not found when sshing into container

### ISSUE THREAD

**Issue by anthonygreen** [docker-library/ruby#51] opened 2015-08-28 12:51 UTC
Dockerfile

    FROM ruby:latest

    RUN apt-get update

    RUN apt-get install -y openssh-server
    RUN mkdir -p /var/run/sshd

    RUN apt-get install -y --no-install-recommends openjdk-7-jdk
    RUN apt-get install -y --no-install-recommends subversion

    RUN adduser --quiet --disabled-login jenkins
    RUN echo "jenkins:password" | chpasswd

    RUN mkdir -p /home/jenkins/.subversion
    RUN mkdir -p /home/jenkins/.ssl 
    RUN mkdir -p /home/jenkins/.ssh

    EXPOSE 22

    CMD ["/usr/sbin/sshd", "-D"]

when I ssh in bundler is not listed amongst `gem list`

nor can any bundle command be run

   sudo docker run -it --rm ruby:latest bundle --version

does state

    Bundler version 1.10.6

though

so maybe some documentation on how it's supposed to work from within the container

**Comment by yosifkit** [comment] 2015-08-28 18:40
`ssh` is scrubbing the environment variables that are setup in the container.  Not sure how you would get it to inject them into the resultant shell.

**Comment by anthonygreen** [comment] 2015-08-28 20:09
Could be connected to https://github.com/docker/docker/issues/2569

**Comment by md5** [comment] 2015-08-28 20:20
I'm not so sure this is specifically related to `ssh`:

```console
$ diff -u <(docker run --rm ruby gem list) <(docker run --rm ruby sh -c 'adduser --quiet --disabled-login --gecos "" someuser && su - someuser -c "gem list"')
--- /dev/fd/63	2015-08-28 13:19:38.000000000 -0700
+++ /dev/fd/62	2015-08-28 13:19:38.000000000 -0700
@@ -1,5 +1,4 @@
 bigdecimal (1.2.6)
-bundler (1.10.6)
 io-console (0.4.3)
 json (1.8.1)
 minitest (5.4.3)
```

**Comment by md5** [comment] 2015-08-28 20:22
@anthonygreen Which user are you sshing as?

Here's the difference in `env` between `root` and a newly added `someuser`:

```console
$ diff -u <(docker run --rm ruby env) <(docker run --rm ruby sh -c 'adduser --quiet --disabled-login --gecos "" someuser && su - someuser -c env')
--- /dev/fd/63	2015-08-28 13:21:10.000000000 -0700
+++ /dev/fd/62	2015-08-28 13:21:10.000000000 -0700
@@ -1,10 +1,9 @@
-PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-HOSTNAME=40dc7f1a125a
-RUBY_MAJOR=2.2
-RUBY_VERSION=2.2.3
-RUBY_DOWNLOAD_SHA256=df795f2f99860745a416092a4004b016ccf77e8b82dec956b120f18bdc71edce
-RUBYGEMS_VERSION=2.4.8
-GEM_HOME=/usr/local/bundle
-BUNDLER_VERSION=1.10.6
-BUNDLE_APP_CONFIG=/usr/local/bundle
-HOME=/root
+SHELL=/bin/bash
+USER=someuser
+MAIL=/var/mail/someuser
+PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
+PWD=/home/someuser
+SHLVL=1
+HOME=/home/someuser
+LOGNAME=someuser
+_=/usr/bin/env
```

**Comment by md5** [comment] 2015-08-28 20:23
I suppose that `su - someuser` is dropping the surrounding environment as well.

**Comment by tianon** [comment] 2015-08-28 20:43
Indeed it is. :wink:

**Comment by md5** [comment] 2015-08-28 20:52
Just to be clear, the missing `GEM_HOME` causes this behavior.

**Comment by md5** [comment] 2015-08-28 20:53
The missing `BUNDLE_APP_CONFIG` probably breaks other stuff.

**Comment by anthonygreen** [comment] 2015-08-29 06:42
@md5 I'm sshing in as 'jenkins', to diagnose why the container can't run bundle in the container when used as a jenkins slave

**Comment by md5** [comment] 2015-08-29 07:24
Is Jenkins connecting to the slave via SSH or are you using dynamically
provisioned slaves?

**Comment by anthonygreen** [comment] 2015-08-29 07:29
@md5 via SSH. It's emerging that in order to get a container based on the official ruby image to work in this manner I will probably need a different approach, since the container is configured as root but the processes are attempting to run as jenkins.

**Comment by anthonygreen** [comment] 2015-08-30 09:25
I thought maybe this would work

    RUN chown -R jenkins /usr/local

    USER jenkins

    RUN gem install bundler

    USER root

but bundler is still missing from the jenkins user's list of installed gems

**Comment by md5** [comment] 2015-08-30 14:34
You'll need to make sure that `GEM_HOME=/usr/local/bundle` is set (and you should probably set `BUNDLE_APP_CONFIG=/usr/local/bundle` too).

```console
$ docker run --rm ruby sh -c 'adduser --quiet --disabled-login --gecos "" someuser && su - someuser -c "GEM_HOME=/usr/local/bundle gem list | grep bundler"'
bundler (1.10.6)
```

**Comment by anthonygreen** [comment] 2015-08-30 20:23
Adding

    RUN echo 'export GEM_PATH=/usr/local:/usr/local/lib/ruby/gems/2.2.0' >> $HOME/.bashrc

to the Dockerfile 

has added bundler to `gem list` when sshing as jenkins user

I'll explore @md5's suggestion next

**Comment by anthonygreen** [comment] 2015-09-01 07:30
$ docker run --rm ruby sh -c 'adduser --quiet --disabled-login --gecos "" someuser \
        && su - someuser -c "GEM_HOME=/usr/local/bundle gem list | grep bundler"'

creates a container that immediately exits

**Comment by md5** [comment] 2015-09-01 13:13
Does it not produce the same output that I posted earlier? That command
should not be expected to be long-running, but it should show that bundler
is in the gem list.

**Comment by tianon** [comment] 2016-08-22 16:54
Given that this is due to `sshd` and/or `su` dropping environment variables (by design), I'm closing this now. :+1:

(and would recommend exploring `docker exec` instead for entering already running containers)

**Closed by tianon** 2016-08-22 16:54 UTC
